version: '3.7'

services:
  nginx:
    build: ./nginx
    container_name: akaunting-web
    ports:
      - 8080:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - app-data:/var/www/akaunting
    networks:
      - akaunting
    restart: unless-stopped

  php:
    build: ./php
    container_name: akaunting-php
    volumes:
      - app-data:/var/www/akaunting
    networks:
      - akaunting
    restart: unless-stopped

  fix_php_permissions:
    image: php:7.4-fpm
    container_name: akaunting-fix-permissions
    command: chown -R www-data:www-data /var/www/akaunting
    volumes:
      - app-data:/var/www/akaunting
    networks:
      - akaunting
    depends_on:
      - php

  db:
    image: mariadb:10.5
    container_name: akaunting-db
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - akaunting
    restart: unless-stopped

#    image: postgres:alpine
#    container_name: akaunting-db
#    volumes:
#      - db-data:/var/lib/postgresql/data
#    environment:
#      POSTGRES_DB: akaunting_db
#      POSTGRES_USER: akaunting_admin
#      POSTGRES_PASSWORD: akaunting_password
#    ports:
#        - "5432:5432"
#    networks:
#      - akaunting

#  adminer:
#    image: adminer:4.7.7
#    container_name: akaunting-adminer
#    ports:
#      - 8081:8080
#    volumes:
#      - ./adminer/designs/hydra/adminer.css:/var/www/html/adminer.css
#    restart: unless-stopped
#    networks:
#      - akaunting

networks:
  akaunting:
    driver: bridge

volumes:
  app-data:
  db-data:
